version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-helen
    environment:
      POSTGRES_USER: helen_artstore
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: helenartstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
